// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYjarDU9cjje70KLsz-YzRxq2BBSEqw_c',
    appId: '1:638749066043:web:0f7cd2437db1fd09cced1e',
    messagingSenderId: '638749066043',
    projectId: 'taxiproj-b2f9d',
    authDomain: 'taxiproj-b2f9d.firebaseapp.com',
    storageBucket: 'taxiproj-b2f9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOiQX5IpdEyrZA4x7HG_N7fbKyRQAp5nE',
    appId: '1:638749066043:android:7a44828f75aad837cced1e',
    messagingSenderId: '638749066043',
    projectId: 'taxiproj-b2f9d',
    storageBucket: 'taxiproj-b2f9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpdmKN1GhZIgr8HgNxIf_bRT1C2CiAtIo',
    appId: '1:638749066043:ios:da04f590ad46adaecced1e',
    messagingSenderId: '638749066043',
    projectId: 'taxiproj-b2f9d',
    storageBucket: 'taxiproj-b2f9d.appspot.com',
    androidClientId: '638749066043-ebtmguv64k44ig9k8mumeo2blbgpcuki.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpdmKN1GhZIgr8HgNxIf_bRT1C2CiAtIo',
    appId: '1:638749066043:ios:da04f590ad46adaecced1e',
    messagingSenderId: '638749066043',
    projectId: 'taxiproj-b2f9d',
    storageBucket: 'taxiproj-b2f9d.appspot.com',
    androidClientId: '638749066043-ebtmguv64k44ig9k8mumeo2blbgpcuki.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYjarDU9cjje70KLsz-YzRxq2BBSEqw_c',
    appId: '1:638749066043:web:3878753f1faa08dbcced1e',
    messagingSenderId: '638749066043',
    projectId: 'taxiproj-b2f9d',
    authDomain: 'taxiproj-b2f9d.firebaseapp.com',
    storageBucket: 'taxiproj-b2f9d.appspot.com',
  );
}
